/**
 * TD3 passport MRZ fixtures. Each `lines` array is two strings of exactly
 * 44 characters. Check digits were computed from the canonical ICAO 9303
 * specimen passport ("Anna Maria Eriksson") and from synthesised specimens
 * whose digits were generated by the same algorithm we test in mrz.ts.
 */
export interface MrzFixture {
  name: string;
  lines: [string, string];
  expected: {
    surname: string;
    givenNames: string;
    fullName: string;
    issuingCountry: string;
    nationality: string;
    passportNumber: string;
    dob: string;
    sex: 'M' | 'F' | '';
    expirationDate: string;
    personalNumber?: string;
  };
  /** When set, the fixture intentionally has a bad digit for that field. */
  expectedFailingChecks?: Array<
    'passportNumber' | 'dob' | 'expiry' | 'personalNumber' | 'composite'
  >;
}

export const mrzFixtures: MrzFixture[] = [
  {
    // ICAO 9303 canonical specimen.
    name: 'ICAO specimen — Anna Maria Eriksson (UTO)',
    lines: [
      'P<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<',
      'L898902C36UTO7408122F1204159ZE184226B<<<<<10',
    ],
    expected: {
      surname: 'ERIKSSON',
      givenNames: 'ANNA MARIA',
      fullName: 'ANNA MARIA ERIKSSON',
      issuingCountry: 'UTO',
      nationality: 'UTO',
      passportNumber: 'L898902C3',
      dob: '1974-08-12',
      sex: 'F',
      expirationDate: '2012-04-15',
      personalNumber: 'ZE184226B',
    },
  },
  {
    name: 'USA — JOHN DOE',
    lines: [
      'P<USADOE<<JOHN<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<',
      '1234567897USA8001014M3001019<<<<<<<<<<<<<<<8',
    ],
    expected: {
      surname: 'DOE',
      givenNames: 'JOHN',
      fullName: 'JOHN DOE',
      issuingCountry: 'USA',
      nationality: 'USA',
      passportNumber: '123456789',
      dob: '1980-01-01',
      sex: 'M',
      expirationDate: '2030-01-01',
      personalNumber: '',
    },
  },
  {
    name: 'GBR — MARY JANE SMITH',
    lines: [
      'P<GBRSMITH<<MARY<JANE<<<<<<<<<<<<<<<<<<<<<<<',
      '5234567895GBR9203158F2812313<<<<<<<<<<<<<<<8',
    ],
    expected: {
      surname: 'SMITH',
      givenNames: 'MARY JANE',
      fullName: 'MARY JANE SMITH',
      issuingCountry: 'GBR',
      nationality: 'GBR',
      passportNumber: '523456789',
      dob: '1992-03-15',
      sex: 'F',
      expirationDate: '2028-12-31',
      personalNumber: '',
    },
  },
  {
    name: 'CAN — JEAN PIERRE TREMBLAY (multi-given-name)',
    lines: [
      'P<CANTREMBLAY<<JEAN<PIERRE<<<<<<<<<<<<<<<<<<',
      'AB12345671CAN8506209M2706203<<<<<<<<<<<<<<<8',
    ],
    expected: {
      surname: 'TREMBLAY',
      givenNames: 'JEAN PIERRE',
      fullName: 'JEAN PIERRE TREMBLAY',
      issuingCountry: 'CAN',
      nationality: 'CAN',
      passportNumber: 'AB1234567',
      dob: '1985-06-20',
      sex: 'M',
      expirationDate: '2027-06-20',
      personalNumber: '',
    },
  },
  {
    name: 'DEU — MARKUS MUELLER',
    lines: [
      'P<DEUMUELLER<<MARKUS<<<<<<<<<<<<<<<<<<<<<<<<',
      'C01X00T478DEU7008120M2606152<<<<<<<<<<<<<<<8',
    ],
    expected: {
      surname: 'MUELLER',
      givenNames: 'MARKUS',
      fullName: 'MARKUS MUELLER',
      issuingCountry: 'DEU',
      nationality: 'DEU',
      passportNumber: 'C01X00T47',
      dob: '1970-08-12',
      sex: 'M',
      expirationDate: '2026-06-15',
      personalNumber: '',
    },
  },
  {
    // Same as USA fixture above but with the DOB check digit corrupted from 4 → 5.
    name: 'USA — JOHN DOE with bad DOB check digit',
    lines: [
      'P<USADOE<<JOHN<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<',
      '1234567897USA8001015M3001019<<<<<<<<<<<<<<<8',
    ],
    expected: {
      surname: 'DOE',
      givenNames: 'JOHN',
      fullName: 'JOHN DOE',
      issuingCountry: 'USA',
      nationality: 'USA',
      passportNumber: '123456789',
      dob: '1980-01-01',
      sex: 'M',
      expirationDate: '2030-01-01',
      personalNumber: '',
    },
    // The DOB digit is wrong, so dob fails AND the composite (which includes
    // that digit) also fails.
    expectedFailingChecks: ['dob', 'composite'],
  },
];
